# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SkyBlog
email: german.nikolishin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikolish.in" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name:         German Nikolishin
  email:        german.nikolishin@gmail.com
  url:          https://nikolish.in

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

related_posts_section:
  max_count:        5
  min_common_tags:  2

paginate: 5

social:
  email: german.nikolishin@gmail.com
  github: https://github.com/SkymanOne
  twitter: https://twitter.com/skyman_one
  linkedin: https://www.linkedin.com/in/skymanone/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
